apiVersion: v1
kind: PersistentVolumeClaim
metadata:
      name: graf-pvc
      labels:
              env: production
spec:
      accessModes:
              - ReadWriteOnce
      resources:
              requests:
                      storage: 1Gi
