apiVersion: v1
kind: Service
metadata:
        name: service-monitor-1
spec:
        selector:
                env: production
        type: NodePort 
        ports:
                - port: 9090
                  protocol: TCP
                  name: port-prom
                - port: 3000
                  protocol: TCP
                  name: port-graf
